sudo: required
language: c
services:
  - docker

script:
# Lint
- docker run -it --rm -v "$PWD/Dockerfile:/Dockerfile:ro" redcoolbeans/dockerlint
- docker run -it --rm -v "$PWD/Dockerfile.onbuild:/Dockerfile:ro" redcoolbeans/dockerlint


after_success:
# Build and deploy
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=gatsbyjs/gatsby
  - export MAIN_TAG=`if [ "$TRAVIS_CURRENT_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_CURRENT_BRANCH ; fi`
  - export ONBUILD_TAG=`if [ "$TRAVIS_CURRENT_BRANCH" == "master" ]; then echo "onbuild"; else echo "${MAIN_TAG}-onbuild" ; fi`
  - docker build -f Dockerfile -t $REPO:$TRAVIS_COMMIT .
  - docker build -f Dockerfile.onbuild -t $REPO:$TRAVIS_COMMIT-onbuild .
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:$MAIN_TAG
  - docker tag $REPO:$TRAVIS_COMMIT-onbuild $REPO:$ONBUILD_TAG

  - docker push $REPO
